name: whimy-publish
run-name: ${{ github.run_id }} tests
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: windows-2019
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Install | Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Lint
        run: cargo clippy

      - name: Setup certificate
        run: .\setting_up_cert_testing.ps1
        shell: powershell
        working-directory: ./test_signed_data/custom_signed
      


      - name: Tests
        run : cargo test
      
      - name: Compile
        run: | 
          yarn install
          yarn build

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
