name: whimy-tests
run-name: ${{ github.run_id }} tests
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: windows-2019
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Install | Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Lint
        run: cargo clippy
      
      - name: Compile | Napi
        run: | 
          yarn install
          yarn build
      - name: Tests
        run : cargo test


